### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [minzen/fullstack_harjoitustyo_frontend#3]
# Katselmointi

### Mitä tein

- Rekisteröidyin, vahvistin sähköpostin ja kirjauduin sisään
- Lisäsin muutaman uuden muistiinpanon, testasin arkistointia, poistoa ja muokkausta
- Testasin hakua ja filtteröintiä
- Kirjauduin ulos

### Kokemus

- Käyttöliittymä on erittäin selkeä ja viimeistelty. Kaikki oleellinen toiminallisuus on toteutettu, hyvä! 
- Lokalisaatio ja sähköpostin vahvistus on erittäin pro 🏆
- Virheviestit on hieman kryptisiä: "Note validation failed: title: Path `title` is required., content: Path `content` is required." jne.
- Muistiinpanon lisäysnappi voisi nousta enemmän esiin, täytyi hieman etsiä
- Sähköpostin vahvistuslinkistä aukeava sivu voi olla käyttäjälle hieman hämmentävä

## Koodi

- Backend-koodin rakenne muuten hyvä, paitsi resolverit voisi siirtää `index.js`-tiedostosta omiin tiedostoihinsa, kuten tyyppi määrittelyillekin on tehty. Resolverit voi mergetä yhdeksi objektiksi esim. lodashin [merge](https://lodash.com/docs/4.17.15#merge)-funktiolla.
- Resolvereiden lisäksi `index.js`-tiedostossa on paljon apufunktionalisuutta, jonka voisi siirtää muualle
- Frontti-puolen koodilla on myös hyvä rakenne
- [Tämän](https://github.com/minzen/fullstack_harjoitustyo_frontend/blob/master/src/App.js#L113) reititysratkaisun sijaan voisi harkita esim. [react-router](https://reacttraining.com/react-router/core/guides/quick-start)-kirjastoa
- `ApolloProvider`-komponenttia ei tarvitse määritelle monta kertaa, ellei jostain syystä halua käyttää eri clienttia: https://github.com/minzen/fullstack_harjoitustyo_frontend/blob/master/src/App.js#L201
- Apollo clienttia ei tarvitse antaa propsina lapsille, käytä mielummin `useApolloClient` hookkia, joka käyttää `ApolloProvider` kontekstia

## Kokonaisuus

- Käyttäjäystävällinen sovellus, josta löytyy tarvittava toiminallisuus ilman suurempia käytettävyysongelmia
- Koodin puolesta pieniä rakenteellisia muutoksia ja refaktorointia, mutta pääosin laadukasta koodia

**Comment by minzen** [comment]
Kiitos paljon palautteesta. Pääosin puutteet ja parannuskohteet olivatkin tiedossa. On hyvä kuitenkin saada palautetta, koska työhön on kuitenkin tullut käytettyä aikaa kohtuullisen paljon ja tietyille asioille tulee helposti sokeaksi...
